### ISSUE TITLE
Add sorting by Featured for jobs in wp-admin.

### ISSUE THREAD

**Issue by denisbaranov** [ultimatemember/jobboardwp#111]
**Describe**
Add a checkmark for jobs that are Featured or a filter to sort such jobs in the list of works in wp-admin.

**Expected behavior**
Ability for admin to see or sort the display of jobs marked as "Featured" in the list of jobs on the "Jobs" page in wp-admin.

**Comment by nikitasinelnikov** [comment]
Filter has to look like this:
https://imgur.com/6qnmwE0
