### ISSUE TITLE
The Notice displays the content of the job.

### ISSUE THREAD

**Issue by denisbaranov** [ultimatemember/jobboardwp#48]
**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
The Notice displays the content of the job on the individual job page.

**Expected behavior**
When visiting a page with a job, the notice should display the content created in the notice content field.

**Screenshots**
https://watch.screencastify.com/v/cKuQ9T8r2iJRYzlTVitf

**Do you use UM extensions?**
- [x] Notices
- [x] JobBoardWP

**Comment by nikitasinelnikov** [comment]
Fixed through this commit https://github.com/ultimatemember/notices/commit/e7a36a3489ba22b565ffee05a877a7e75289c362
