### ISSUE TITLE
Doesn't change display_name for jobs.

### ISSUE THREAD

**Issue by denisbaranov** [ultimatemember/jobboardwp#82]
**Describe the bug**
When creating a new job with changing the data in the First name/Last name fields, the job is displayed without the changed data in these fields.
The data is displayed unchanged also in wp-admin, on the "Jobs" page (WP-Admin > Job Board > Jobs)

**To Reproduce**
https://watch.screencastify.com/v/g5uqQYJaa5OHBg7intB3

**Comment by nikitasinelnikov** [comment]
See the custom snippet for this fix here:
https://gist.github.com/nikitasinelnikov/64b90a3873ec2ffe26d166ea00e6ba13
